[Abstract, 
 version("1.0.0"), 
 Description (
    "Credential to use for DSC configuration providers." )]
class MSFT_BaseCredential 
{   
        [Description 
            ("UserName is the name of the user for an authorization service to map to an identity." ), 
         MaxLen ( 256 )]
    string UserName;
        [Description
        ("UserPassword property may contain a passwordused to access resources." )]
    string Password;
};

[version("1.0.0"), Description ("Credential to use for DSC configuration providers on Windows")]
class MSFT_WindowsCredential : MSFT_BaseCredential
{   
        [Description 
            ("Domain name of the user if it below to a LDAP directory." ), 
         MaxLen ( 256 )]
    string Domain;
};

