#!/bin/sh

run_char=1
run_size=1
run_check=1

##==============================================================================
##
## Get command line options that start with dash:
##
##==============================================================================
for opt
do

  arg=`expr "x$opt" : 'x[^=]*=\(.*\)'`

  case $opt in

    -h | --help)
      help=1
      ;;

    --runs=*)
        run_char=0
        run_wchar=0
        run_size=0
        run_check=0
        runs=`echo $arg | sed 's/:/ /g'`
        for i in $runs
        do
            case $i in
                char)
                    run_char=1
                    ;;
                size)
                    run_size=1
                    ;;
                check)
                    run_check=1
                    ;;
                all)
                    run_char=1
                    run_wchar=1
                    run_size=1
                    run_check=1
                    ;;
                *)
                    echo "$0: unknown option argument for --runs:  $i"
                    exit 1
            esac
        done
        ;;
      
    *)
      echo "$0: unknown option:  $opt"
      exit 1
      ;;

  esac
done

##=============================================================================
##
## Handle --help option:
##
##==============================================================================

if [ "$help" = "1" ]; then

    cat<<EOF

Usage: ./regress [OPTIONS] TESTNAME(S)

OVERVIEW:

Runs regression tests for OMI.

    $ ./regress [OPTIONS] TESTNAME(S)

OPTIONS:
    -h, --help              Print this help message.
    --enable-ut             Enable UT tests.
    --runs=TESTNAME(S)  Run only those test runs
TESTNAME(S):
    char                  run (single byte) char tests run
    size                  run (optimized for) size tests run
    check                 run check tests run
    all                   run all test runs (char, wchar, size, check)

Examples:
       ./regress
       ./regress --runs=char:size
       
EOF
    exit 0
fi

##==============================================================================
##
## Determine configure and root directories:
##
##==============================================================================

root=`dirname $0`

##==============================================================================
##
## 'dscworld' tests
##
##==============================================================================

if [ "$run_char" = "1" ]; then

rm -rf ./output1 GNUmakefile
$root/configure --dev --enable-dsc --outputdirname=output1 $options
make dscworld

if [ "$?" != "0" ]; then
    echo "$0: failed 'dscworld' tests"
    exit 1
fi

rm -rf ./output1 GNUmakefile

fi

##==============================================================================
##
## 'size' tests
##
##==============================================================================

if [ "$run_size" = "1" ]; then

rm -rf ./output3 GNUmakefile
$root/configure --dev  --enable-dsc --favorsize --outputdirname=output3  $options
make dscworld

if [ "$?" != "0" ]; then
    echo "$0: failed 'size' tests"
    exit 1
fi

rm -rf ./output3 GNUmakefile

fi

##==============================================================================
##
## SUCCESS
##
##==============================================================================

echo ""
echo ""
echo "##===================##"
echo "##                   ##"
echo "## ALL TESTS PASSED! ##"
echo "##                   ##"
echo "##===================##"
echo ""
exit 0
