/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxEnvironmentResource as $MSFT_nxEnvironmentResource1ref
{
  ResourceID = "[nxEnvironment]myTestEnvironment";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  Name = "test";
  Ensure = "Absent";
  Value = "/test";
  Path = True;
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

