/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxIPAddressResource as $MSFT_nxIPAddressResource1ref
{
  ResourceID = "[nxIPAddress]myTestIPAddress";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  IPAddress = "100.112.158.47";
  InterfaceName="eth1";
  BootProtocol="Static";
  DefaultGateway="100.112.158.1";
  Ensure="Present";
  PrefixLength=23;
  AddressFamily="IPv4";
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

