/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxScriptResource as $MSFT_nxScriptResource1ref
{
  ResourceID = "[nxScript]myTestFile";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  SetScript =  "#!/bin/bash\nrm -rf /tmp/mydir/*";
  GetScript =  "#!/bin/bash\nls /tmp/mydir/ | wc -l";
  TestScript = "#!/bin/bash\nfilecount=ls /tmp/mydir/ | wc -l\nif [  -gt 0 ]\nthen\n    exit 1\nelse\n    exit 0\nfi";
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

