/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxUserResource as $MSFT_nxUserResource1ref
{
  ResourceID = "[nxUser]myTestUser";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  UserName = "jojoma";
  Ensure = "Present";
  FullName = "JO JO MA";
  Description = "JOJOMA";
  Password = "F5L7jHK1zN4yARUyQ6ulTIytFHxxeDZv";
  HomeDirectory = "/home/jojoma";
  GroupID = "mail";
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

