DSCTOP = ../../..
TOP = ../../../..
include $(TOP)/config.mak

LIBRARY = CALogInfrastructure

SOURCES = \
	CALog.c 

INCLUDES = \
	 $(TOP) \
	$(TOP)/common \
	$(DSCTOP)/common/inc \
	$(DSCTOP)/engine/EngineHelper \
	$(TOP)/codec/common \
	$(TOP)/nits/base

DEFINES = MI_CONST= HOOK_BUILD

include $(TOP)/mak/rules.mak
