TOP = ..
include $(TOP)/config.mak

LIBRARY = mofparsererror

SOURCES = errors.c errorswrap.c omiutils.c

INCLUDES = $(OMI) $(OMI)/common

DEFINES =  MI_CONST= $(BUILD_OMS)

# LIBRARIES = base

include $(OMI)/mak/rules.mak

