#pragma include ("OMI_BaseResource.mof")
#pragma include ("MSFT_Credential.mof")

[ClassVersion("1.0.0"), FriendlyName("nxUser")]
class OMI_nxUserResource : OMI_BaseResource 
{
	[Key] string UserName;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
	[write] string FullName;
	[write] string Description;
	[write] string Password;
	[write] boolean Disabled;
	[write] boolean PasswordChangeRequired;
	[write] string HomeDirectory;
	[write] string GroupID;

	[static,
         Description (
             "Get resource states based on input configuration file." )]
    uint32 GetTargetResource(
            [in,
             EmbeddedInstance ("OMI_nxUserResource"),
             Description (
                "Configuration document that is to be applied." )]
        string InputResource,

            [in,
             Description (
                "Flags passed to the providers. Reserved for future use." )]
        uint32 Flags,
            [out,
             EmbeddedInstance ("OMI_nxUserResource"),
             Description (
                "The current state of the specified configuration resources." )]
        string OutputResource
        );

    [static,
         Description (
             "Test resource states based on input configuration file." )]
    uint32 TestTargetResource(
            [in,
             EmbeddedInstance("OMI_nxUserResource"),
             Description (
                "Configuration document that to be applied." )]
        string InputResource,    
            [in, 
             Description (
                "Flags passed to the providers. reserved for future use." )]
        uint32 Flags,   
            [out,
             Description (
                "True if identical. False otherwise." )]
        boolean Result,     
            [out,
             Description (
                "Context information that the provider can use to optimize the set, This is optional." )]
        uint64 ProviderContext
        );

    [static,
         Description (
            "Set resource states based on input configuration file." )]
    uint32 SetTargetResource(
            [in,
             EmbeddedInstance ("OMI_nxUserResource"),
             Description (
                "Configuration document that to be applied." )]
        string InputResource,    
            [in,
             Description (
                "Context information that the provider can use to optimize the set from TestTargetResource, This is optional." )]
        uint64 ProviderContext,
            [in,
             Description (
                "Flags passed to the providers. reserved for future use." )]
        uint32 Flags
		);
};
