

[ClassVersion("1.0.0"), FriendlyName("nxComputerResource")] 
class MSFT_nxComputerResource : OMI_BaseResource
{
    [key] string Name;
    [Write] string DNSDomainName;
    [Write] string TimeZoneName;
    [Write] string AlternateTimeZoneName;

};
		
