TOP = ..
include $(TOP)/config.mak

CXXSHLIBRARY = httpclientcxx

SOURCES = httpclientcxx.cpp

INCLUDES = $(TOP) $(TOP)/common

LIBRARIES = protocol sock base

DEFINES = BUILDING_HTTPCLIENT

include $(TOP)/mak/rules.mak
