DSCTOP = ../..
TOP = ../../..
include $(TOP)/config.mak

CPROGRAM = ConsistencyInvoker
SOURCES = ConsistencyInvoker.c

INCLUDES = $(OMI) $(OMI)/common $(TOP)/codec/common $(OMI)/nits/base $(DSCTOP)/common/inc $(DSCTOP)/engine/EngineHelper 

LIBRARIES = mi $(PALLIBS)

include $(OMI)/mak/rules.mak
