DSCTOP = ../..
TOP = ../../..
include $(TOP)/config.mak
CPROGRAM = consistencyinvoker
SOURCES = ConsistencyInvoker.c

INCLUDES = $(TOP) $(TOP)/common $(TOP)/codec/common $(TOP)/nits/base $(DSCTOP)/common/inc $(DSCTOP)/engine/EngineHelper 

LIBRARIES = mi $(PALLIBS)

include $(TOP)/mak/rules.mak
