[Abstract, 
 ClassVersion("1.0.0"), 
 Description (
    "Credential to use for DSC configuration providers." )]
class MSFT_Credential 
{   
        [Description 
            ("UserName is the name of the user that an authorization service maps to an identity." ), 
         MaxLen ( 256 )]
    string UserName;
        [Description
        ("The UserPassword property may contain a password used to access resources." )]
    string Password;
};



