


[ClassVersion("1.0.0"), FriendlyName("nxFirewall")]
class MSFT_nxFirewallResource:OMI_BaseResource
{
       [Key] string Name;
       [Write] string InterfaceName;
       [Write, required, ValueMap{"Iptables", "Ip6tables", "yast", "ufw", "susefirewall2", "firewalld"}, Values{"Iptables", "Ip6tables", "yast", "ufw", "susefirewall2", "firewalld"}] string FirewallType; 
       [Write, ValueMap{"tcp", "udp", "icmp"}, Values{"tcp", "udp", "icmp"}] string Protocol;
       [Write, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
       [Write, ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
       [Write, required, ValueMap{"Allow", "Block"},Values{"Allow", "Block"}] string Access;
       [Write, ValueMap{"ESTABLISHED", "RELATED", "NEW"},Values{"ESTABLISHED", "RELATED", "NEW"}] string State[];
       [Write, ValueMap{"INPUT", "OUTPUT", "FORWARD"},Values{"INPUT", "OUTPUT", "FORWARD"}] string Direction;
       [Write] string SourceHost;
       [Write] string SourcePort;
       [Write] string DestinationHost;
       [Write] string DestinationPort;
       [Write, ValueMap{"top", "after-top", "before-end", "end"},Values{"top", "after-top", "before-end", "end"}] string Position;
};


