instance of TestNonDependent
{
    ResourceId = "a";
    ModuleName="PsModuleForTestNonDependent";
    ModuleVersion="1.0";
    bFail = true;
    Id1 = "10";
};

instance of TestNonDependent
{
    ResourceId = "b";
    ModuleName="PsModuleForTestNonDependent";
    ModuleVersion="1.0";
    bFail = true;
    Id1 = "11";
};

instance of TestNonDependent
{
    ResourceId = "c";
    ModuleName="PsModuleForTestNonDependent";
    ModuleVersion="1.0";
    bFail = true;
    Id1 = "12";
};


instance of OMI_ConfigurationDocument
{
    Version="1.0.0";
    
};
