#CodeQL [python/responsible-ai/using-python2] old python version: support still needed for older python version
UNKNOWN = "Unknown"
MANUAL = "Manual"
TESTDRAFT = "TestDraft"
SCHEDULED = "Scheduled"
WEBHOOK = "Webhook"
INTERNAL = "Internal"
WATCHER = "Watcher"
UNKNOWN_ENUM_INDEX = 0
MANUAL_ENUM_INDEX = 1
TESTDRAFT_ENUM_INDEX = 2
SCHEDULED_ENUM_INDEX = 3
WEBHOOK_ENUM_INDEX = 4
INTERNAL_ENUM_INDEX = 5
WATCHER_ENUM_INDEX = 6

mapping = {
    UNKNOWN_ENUM_INDEX: UNKNOWN,
    MANUAL_ENUM_INDEX: MANUAL,
    TESTDRAFT_ENUM_INDEX: TESTDRAFT,
    SCHEDULED_ENUM_INDEX: SCHEDULED,
    WEBHOOK_ENUM_INDEX: WEBHOOK,
    INTERNAL_ENUM_INDEX: INTERNAL,
    WATCHER_ENUM_INDEX: WATCHER
}
