TOP = .

include $(TOP)/config.mak

DIRECTORIES = omiutils
DIRECTORIES += codec/mof
DIRECTORIES += codec/mof/parser
DIRECTORIES += dsc/engine/EngineHelper
DIRECTORIES += dsc/engine/ca/CAInfrastructure
DIRECTORIES += dsc/engine/ca/CALogInfrastructure
DIRECTORIES += dsc/engine/ConfigurationManager
DIRECTORIES += dsc/engine/ModuleLoader/ModuleLibrary
DIRECTORIES += dsc/engine/lcm
DIRECTORIES += dsc/engine/ConsistencyInvoker
TESTDIRS += dsc/tests/Engine/TestProvider
TESTDIRS += dsc/tests/Engine/TestFileProvider
TESTDIRS += dsc/tests/Engine/CA
TESTDIRS += dsc/tests/Engine/ModuleLoader
TESTDIRS += dsc/tests/Engine/LCM
TESTDIRS += dsc/tests/Engine/E2E

include $(OMI)/mak/rules.mak
