[Description(
	"This represents a Partial Configuration class."),
	ClassVersion("1.0.0")]
class MSFT_PartialConfiguration : OMI_MetaConfigurationResource 
{
	[Description ("Description of the partial configuration" )  , Write] 
	String Description ; 

	[Description ("Defines the resources that are exclusive to this particular partial configuration" )  , Write] 
	String ExclusiveResources[]; 
 
	[Description ("The configuration repository source that this partial configuration will use" )  , Write] 
	String ConfigurationSource[]; 

   	[Description ("The resource module repository source that this partial configuration will use" )  , Write] 
   	String ResourceModuleSource[]; 

   	[Description ("A dependency variable indicating which partial configuration must be applied prior to this" )  , Write] 
   	String DependsOn[];    
   
   	[Description ("The refresh mode for the server. Valid values are Pull, Push and Disabled." ) ,
   	ValueMap {"Push","Pull","Disabled"},
   	Values {"Push","Pull","Disabled"}]
   	string  RefreshMode;	      
};
