[ClassVersion("1.0.0"), FriendlyName("LocalConfigurationManager")] 
class MSFT_DSCMetaConfiguration
{
  uint32 ConfigurationModeFrequencyMins;
  boolean RebootNodeIfNeeded = FALSE;
  [ValueMap {"ApplyOnly","ApplyAndMonitor","ApplyAndAutoCorrect"}, Values {"ApplyOnly","ApplyAndMonitor","ApplyAndAutoCorrect"}]
  string ConfigurationMode;
  [EmbeddedInstance("MSFT_Credential")] string Credential;
  [ValueMap {"Push","Pull"}, Values {"Push","Pull"}]
  string RefreshMode;
  string CertificateID;
  string ConfigurationID;
  string DownloadManagerName;
  [EmbeddedInstance("MSFT_KeyValuePair")] string DownloadManagerCustomData[];
  uint32 RefreshFrequencyMins;
  boolean AllowModuleOverwrite;
  
  [Description ("Array of configuration download manager objects that contain location information to download configurations" ) ,
  EmbeddedInstance("OMI_ConfigurationDownloadManager")]
  string  ConfigurationDownloadManagers[];    

  [Read,ValueMap{"Ready","Busy","PendingReboot"}, Values{"Ready","Busy","PendingReboot"}] string LocalConfigurationManagerState;
  [EmbeddedInstance("MSFT_PartialConfiguration")] string PartialConfigurations[];
};
