[ClassVersion("1.0.0"), Description("The configuration provider for program and shell command execution."), FriendlyName("nxExec")]
class MSFT_nxExecResource:OMI_BaseResource
{
  [key] string Command;
  [write] string Environment[];
  [write] boolean Shell;
  [write] uint16 Returncode;
  [write] uint32 Timeout;
  [write] string User;
  [write] string Group;
  [write] string TestCommand;
};
