DSCTOP = ../../..
TOP = ../../../..
include $(TOP)/config.mak

LIBRARY = ModuleHandler

SOURCES = \
	ModuleHandler.c \
	ModuleValidator.c 

INCLUDES = $(TOP) $(TOP)/common $(DSCTOP)/common/inc $(DSCTOP)/engine/EngineHelper $(DSCTOP)/engine $(TOP)/codec/common $(TOP)/nits/base

DEFINES = MI_CONST= HOOK_BUILD

include $(TOP)/mak/rules.mak

