/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxIPAddressResource as $MSFT_nxIPAddressResource1ref
{
  ResourceID = "[nxIPAddress]myTestIPAddress";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  IPAddress = "2002:0:0:0:0:0:6470:9e2f";
  InterfaceName="eth0";
  BootProtocol="Static";
  DefaultGateway="2002:0:0:0:0:0:6470:9e01";
  Ensure="Present";
  PrefixLength=23;
  AddressFamily="IPv6";
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

