[ClassVersion("1.0.0"),FriendlyName("nxMySqlDatabase")] 
class MSFT_nxMySqlDatabaseResource : OMI_BaseResource
{
    [Key, Description("Name of the database.")] String Name;
    [Write, Description("Should the database be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The root credential that is used to install MySql server.")] String ConnectionCredential;
};
