instance of MSFT_FileDirectoryConfiguration
{
    ResourceId = "Res1";
    ModuleName="PSDesiredStateConfiguration";
    ModuleVersion="1.0";
    DestinationPath = "C:\\ModuleLoader.txt";
    Ensure = "File";
    contents="DDDD";
    checksum = "sha-1";
};

instance of MSFT_FileDirectoryConfiguration
{
    ResourceId = "Res2";
    ModuleName="PSDesiredStateConfiguration";
    ModuleVersion="1.0";
    DestinationPath = "C:\\ModuleLoader2.txt";
    Ensure = "File";
    contents="DDDD";
    checksum = "sha-1";
};



instance of OMI_ConfigurationDocument
{
	Version="1.0.0";
};
