
/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxArchiveResource as $MSFT_nxArchiveResource1ref
{
  ResourceID = "[nxArchive]myTestFile";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  SourcePath = "/tmp/src.zip";
  DestinationPath = "/tmp/dest_zip";
  Ensure = "Present";
  Checksum="mtime";
/*   Checksum="md5"; */
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

