/*
@TargetNode='10.0.2.2'
@GeneratedBy=matt
@GenerationDate=01/07/2015 15:32:47
@GenerationHost=EGWIN7
*/

instance of MSFT_nxIPAddressResource as $MSFT_nxIPAddressResource1ref
{
  ResourceID = "[nxIPAddress]myTestIPAddress";
  ModuleName = "nx";
  ModuleVersion = "1.0";
  IPAddress="";
  InterfaceName="eth1";
  BootProtocol="Automatic";
  Ensure="Present";
  AddressFamily="IPv6";
};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="matt";
 GenerationDate="01/07/2015 15:32:47";
 GenerationHost="EGWIN7";
};

