
Instance of MSFT_CimConfigurationProviderRegistration
{
  className = "MSFT_nxOMSInventoryMOFResource";
  DSCEngineCompatVersion = "1.0.0";
  DSCModuleVersion = "1.0.0";
  Namespace = "root/oms";
};

