[ClassVersion("1.0.0"), FriendlyName("nxGroup")]
class OMI_nxGroupResource:OMI_BaseResource
{
	[Key] string GroupName;
	[Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
	[Write] string Members[];
	[Write] string MembersToInclude[];
	[Write] string MembersToExclude[];
	[Write] string PreferredGroupID;
};
