instance of MSFT_DSCMetaConfiguration
{
    ConfigurationModeFrequencyMins = 30;
    RebootNodeIfNeeded = False;
    ConfigurationMode = "ApplyAndMonitor";
    RefreshMode = "PUSH";
    RefreshFrequencyMins = 15;
    AllowModuleOverwrite = False;
    LocalConfigurationManagerState = "Busy";
};

