instance of Linux_File { ResourceId = "[Linux_File]MyFileExample1"; DestinationPath = "/tmp/dsctest/linuxfile1"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample2"; DestinationPath = "/tmp/dsctest/linuxfile2"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample3"; DestinationPath = "/tmp/dsctest/linuxfile3"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample4"; DestinationPath = "/tmp/dsctest/linuxfile4"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample5"; DestinationPath = "/tmp/dsctest/linuxfile5"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample6"; DestinationPath = "/tmp/dsctest/linuxfile6"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample7"; DestinationPath = "/tmp/dsctest/linuxfile7"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample8"; DestinationPath = "/tmp/dsctest/linuxfile8"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample9"; DestinationPath = "/tmp/dsctest/linuxfile9"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample10"; DestinationPath = "/tmp/dsctest/linuxfile10"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample11"; DestinationPath = "/tmp/dsctest/linuxfile11"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample12"; DestinationPath = "/tmp/dsctest/linuxfile12"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample13"; DestinationPath = "/tmp/dsctest/linuxfile13"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample14"; DestinationPath = "/tmp/dsctest/linuxfile14"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample15"; DestinationPath = "/tmp/dsctest/linuxfile15"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample16"; DestinationPath = "/tmp/dsctest/linuxfile16"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample17"; DestinationPath = "/tmp/dsctest/linuxfile17"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample18"; DestinationPath = "/tmp/dsctest/linuxfile18"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample19"; DestinationPath = "/tmp/dsctest/linuxfile19"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample20"; DestinationPath = "/tmp/dsctest/linuxfile20"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample21"; DestinationPath = "/tmp/dsctest/linuxfile21"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample22"; DestinationPath = "/tmp/dsctest/linuxfile22"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample23"; DestinationPath = "/tmp/dsctest/linuxfile23"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample24"; DestinationPath = "/tmp/dsctest/linuxfile24"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample25"; DestinationPath = "/tmp/dsctest/linuxfile25"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample26"; DestinationPath = "/tmp/dsctest/linuxfile26"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample27"; DestinationPath = "/tmp/dsctest/linuxfile27"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample28"; DestinationPath = "/tmp/dsctest/linuxfile28"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample29"; DestinationPath = "/tmp/dsctest/linuxfile29"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample30"; DestinationPath = "/tmp/dsctest/linuxfile30"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample31"; DestinationPath = "/tmp/dsctest/linuxfile31"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample32"; DestinationPath = "/tmp/dsctest/linuxfile32"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample33"; DestinationPath = "/tmp/dsctest/linuxfile33"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample34"; DestinationPath = "/tmp/dsctest/linuxfile34"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample35"; DestinationPath = "/tmp/dsctest/linuxfile35"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample36"; DestinationPath = "/tmp/dsctest/linuxfile36"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample37"; DestinationPath = "/tmp/dsctest/linuxfile37"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample38"; DestinationPath = "/tmp/dsctest/linuxfile38"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample39"; DestinationPath = "/tmp/dsctest/linuxfile39"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample40"; DestinationPath = "/tmp/dsctest/linuxfile40"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample41"; DestinationPath = "/tmp/dsctest/linuxfile41"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample42"; DestinationPath = "/tmp/dsctest/linuxfile42"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample43"; DestinationPath = "/tmp/dsctest/linuxfile43"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample44"; DestinationPath = "/tmp/dsctest/linuxfile44"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample45"; DestinationPath = "/tmp/dsctest/linuxfile45"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample46"; DestinationPath = "/tmp/dsctest/linuxfile46"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample47"; DestinationPath = "/tmp/dsctest/linuxfile47"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample48"; DestinationPath = "/tmp/dsctest/linuxfile48"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample49"; DestinationPath = "/tmp/dsctest/linuxfile49"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample50"; DestinationPath = "/tmp/dsctest/linuxfile50"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample51"; DestinationPath = "/tmp/dsctest/linuxfile51"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample52"; DestinationPath = "/tmp/dsctest/linuxfile52"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample53"; DestinationPath = "/tmp/dsctest/linuxfile53"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample54"; DestinationPath = "/tmp/dsctest/linuxfile54"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample55"; DestinationPath = "/tmp/dsctest/linuxfile55"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample56"; DestinationPath = "/tmp/dsctest/linuxfile56"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample57"; DestinationPath = "/tmp/dsctest/linuxfile57"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample58"; DestinationPath = "/tmp/dsctest/linuxfile58"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample59"; DestinationPath = "/tmp/dsctest/linuxfile59"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample60"; DestinationPath = "/tmp/dsctest/linuxfile60"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample61"; DestinationPath = "/tmp/dsctest/linuxfile61"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample62"; DestinationPath = "/tmp/dsctest/linuxfile62"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample63"; DestinationPath = "/tmp/dsctest/linuxfile63"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample64"; DestinationPath = "/tmp/dsctest/linuxfile64"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample65"; DestinationPath = "/tmp/dsctest/linuxfile65"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample66"; DestinationPath = "/tmp/dsctest/linuxfile66"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample67"; DestinationPath = "/tmp/dsctest/linuxfile67"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample68"; DestinationPath = "/tmp/dsctest/linuxfile68"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample69"; DestinationPath = "/tmp/dsctest/linuxfile69"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample70"; DestinationPath = "/tmp/dsctest/linuxfile70"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample71"; DestinationPath = "/tmp/dsctest/linuxfile71"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample72"; DestinationPath = "/tmp/dsctest/linuxfile72"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample73"; DestinationPath = "/tmp/dsctest/linuxfile73"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample74"; DestinationPath = "/tmp/dsctest/linuxfile74"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample75"; DestinationPath = "/tmp/dsctest/linuxfile75"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample76"; DestinationPath = "/tmp/dsctest/linuxfile76"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample77"; DestinationPath = "/tmp/dsctest/linuxfile77"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample78"; DestinationPath = "/tmp/dsctest/linuxfile78"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample79"; DestinationPath = "/tmp/dsctest/linuxfile79"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample80"; DestinationPath = "/tmp/dsctest/linuxfile80"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample81"; DestinationPath = "/tmp/dsctest/linuxfile81"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample82"; DestinationPath = "/tmp/dsctest/linuxfile82"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample83"; DestinationPath = "/tmp/dsctest/linuxfile83"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample84"; DestinationPath = "/tmp/dsctest/linuxfile84"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample85"; DestinationPath = "/tmp/dsctest/linuxfile85"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample86"; DestinationPath = "/tmp/dsctest/linuxfile86"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample87"; DestinationPath = "/tmp/dsctest/linuxfile87"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample88"; DestinationPath = "/tmp/dsctest/linuxfile88"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample89"; DestinationPath = "/tmp/dsctest/linuxfile89"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample90"; DestinationPath = "/tmp/dsctest/linuxfile90"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample91"; DestinationPath = "/tmp/dsctest/linuxfile91"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample92"; DestinationPath = "/tmp/dsctest/linuxfile92"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample93"; DestinationPath = "/tmp/dsctest/linuxfile93"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample94"; DestinationPath = "/tmp/dsctest/linuxfile94"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample95"; DestinationPath = "/tmp/dsctest/linuxfile95"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample96"; DestinationPath = "/tmp/dsctest/linuxfile96"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample97"; DestinationPath = "/tmp/dsctest/linuxfile97"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample98"; DestinationPath = "/tmp/dsctest/linuxfile98"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample99"; DestinationPath = "/tmp/dsctest/linuxfile99"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };
instance of Linux_File { ResourceId = "[Linux_File]MyFileExample100"; DestinationPath = "/tmp/dsctest/linuxfile100"; Contents = "linux file\n"; Ensure = "file";  ModuleName = "PSDesiredStateConfiguration"; ModuleVersion = "1.0"; };

instance of OMI_ConfigurationDocument
{
  Version="1.0.0";
 Author="johnkord";
 GenerationHost="JKORDIC-1";
};

