instance of MSFT_nxFileResource
{
	Contents = "linux file contents\n";
	DestinationPath = "/tmp/linux.txt";
	Ensure = "Present";
	Type = "File";
	Owner = "johnkord";
	Group = "johnkord";
	Mode = "644";
	ResourceId = "[OMI_nxFileResource]File1";
	ModuleName = "PSDesiredStateConfiguration";
	ModuleVersion = "1.0";
	
	
};

instance of MSFT_nxFileResource
{
	DestinationPath = "/tmp/dsctest";
	SourcePath = "/tmp/dsctest_old";
	Ensure = "Present";
	Type = "Directory";
	Owner = "johnkord";
	Group = "johnkord";
	Mode = "744";
	Recurse = "True";
	ResourceId = "[OMI_nxFileResource]File2";
	ModuleName = "PSDesiredStateConfiguration";
	ModuleVersion = "1.0";
	
	
};

instance of OMI_ConfigurationDocument
{
  Version="1.0.0";
  
};

