instance of MSFT_nxFileResource
{
	Contents = "linux file contents\n";
	DestinationPath = "/tmp/linux.txt";
	Ensure = "Present";
	Type = "File";
	Owner = "root";
	Group = "root";
	Mode = "644";
	ResourceId = "[MSFT_nxFileResource]File1";
	ModuleName = "nx";
	ModuleVersion = "1.0";
	
	
};

instance of MSFT_nxFileResource
{
	DestinationPath = "/tmp/dsctest_old";
	Ensure = "Present";
	Type = "Directory";
	ResourceId = "[MSFT_nxFileResource]Dir1";
	ModuleName = "nx";
	ModuleVersion = "1.0";
	
	
};

instance of MSFT_nxFileResource
{
	DestinationPath = "/tmp/dsctest";
	SourcePath = "/tmp/dsctest_old";
	Ensure = "Present";
	Type = "Directory";
	Owner = "root";
	Group = "root";
	Mode = "744";
	Recurse = True;
	ResourceId = "[MSFT_nxFileResource]Dir2";
	ModuleName = "nx";
	ModuleVersion = "1.0";
	
	
};

instance of OMI_ConfigurationDocument
{
  Version="1.0.0";
  
};

