instance of MSFT_nxUserResource
{
	UserName = "testuser";
	Disabled = true;
	PasswordChangeRequired = true;
	Password = "$abcdef";
	Ensure = "Present";
	Description = "DESCRIBED";
	HomeDirectory = "/home/testdir";
	GroupID = "0";
	FullName = "Dr. Test User";
	
	ResourceId = "[MSFT_nxUserResource]Test";
	ModuleName = "nx";
	ModuleVersion = "1.0";
	
	
};

instance of OMI_ConfigurationDocument
{
  Version="1.0.0";
  
};

